### ISSUE TITLE
Migrating old data that is not encrypted.

### ISSUE THREAD

**Issue by ZkHaider** [prashantsolanki3/Secure-Pref-Manager#1]
What strategy would you recommend for migrating old data that is not encrypted, or does this library handle that already? If not I am willing to do a pull request to help out!

**Comment by prashantsolanki3** [comment]
@ZkHaider Hey!
Migration is not supported right now.
According to the present scenario you'll have to migrate the data manually with the help of keys present in the preference file.
I'm glad that you're willing to contribute. I've updated the repo with some changes. 
Do pull the changes before creating a Pull Request. :smiley:

**Comment by prashantsolanki3** [comment]
@ZkHaider Version 1.0.0 supports Preference Migration. [Check it out](https://github.com/prashantsolanki3/Secure-Pref-Manager/tree/f91a8b6233acd56f533cb7cc4d3158a056e3beb1)
