### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by nishu3389** [prashantsolanki3/Secure-Pref-Manager#3]
Failed to resolve: com.github.prashantsolanki3:Secure-Pref-Manager:0.25+

i have added 
maven { url "https://jitpack.io" } 
to maven
and
compile 'com.github.prashantsolanki3:Secure-Pref-Manager:0.25+' 
dependency to build.gradle

**Comment by prashantsolanki3** [comment]
@nishu3389 Try cleaning and rebuilding your project.
If the problem persists then upload your gradle file.

**Comment by nishu3389** [comment]
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "app.volleyexample"
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.mcxiaoke.volley:library-aar:1.0.0'
    compile 'cn.pedant.sweetalert:library:1.3'
    compile 'com.android.support:design:23.1.1'
    compile 'com.github.prashantsolanki3:Secure-Pref-Manager:0.25+'
}
`

**Comment by nishu3389** [comment]
```
 apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "app.volleyexample"
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.mcxiaoke.volley:library-aar:1.0.0'
    compile 'cn.pedant.sweetalert:library:1.3'
    compile 'com.android.support:design:23.1.1'
    compile 'com.github.prashantsolanki3:Secure-Pref-Manager:0.25+'
}
```

**Comment by nishu3389** [comment]
```
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find any matches for com.github.prashantsolanki3:Secure-Pref-Manager:0.25+ as         no versions of com.github.prashantsolanki3:Secure-Pref-Manager are available.
 Searched in the following locations:
     https://jcenter.bintray.com/com/github/prashantsolanki3/Secure-Pref-Manager/maven-    metadata.xml
     https://jcenter.bintray.com/com/github/prashantsolanki3/Secure-Pref-Manager/
     file:/D:/adt-bundle-windows-x86_64-    20140702/sdk/extras/android/m2repository/com/github/prashantsolanki3/Secure-Pref-    Manager/maven-metadata.xml
      file:/D:/adt-bundle-windows-x86_64- 20140702/sdk/extras/android/m2repository/com/github/prashantsolanki3/Secure-Pref-Manager/
     file:/D:/adt-bundle-windows-x86_64-20140702/sdk/extras/google/m2repository/com/github/prashantsolanki3/Secure-Pref-Manager/maven-metadata.xml
     file:/D:/adt-bundle-windows-x86_64-20140702/sdk/extras/google/m2repository/com/github/prashantsolanki3/Secure-Pref-Manager/
 Required by:
     VolleyExample:app:unspecified
```

**Comment by prashantsolanki3** [comment]
@nishu3389 Hey! You module gradle file seems fine, but your log says that it's searching in jcenter and local repo. You might have forgotten adding

`allprojects {
        repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }`

To you project gradle. Check it once and let me know.

**Comment by nishu3389** [comment]
okay thanks, now its working fine, tell me why we need to initialize it before using and whats the role of context in initialization.

and is this class only able to save string values or we can also store int,boolean etc. ??

**Comment by prashantsolanki3** [comment]
@nishu3389 you need to initialize it before using because at the time of initialization you set the encryptor you want to use.
Context is used to Initialize the encryptor and in other internal methods.

You can store string, integer, boolean, long, float for now.
